system:
  units: imperial  # Defaults to 'metric' if set to anything other than 'imperial'.
  system_name: CobraBay1  # ID of the system. Will be used for MQTT client ID, as well as name in MQTT Topics.
  network: True  # Connect to the network at all?
  interface: eth0  # Interface used to uplink. This will be monitored.
  homeassistant: True # Integrate with Home Assistant. If yes, will send discovery messages.
  # Logging definition
  logging:
    console: False
    file: True
#    file_path: Something
#    syslog: Something else
    # Default level for the system. If not included, will default to WARNING.
    default_level: warning
    # Major components can have logging levels set separately. These are:
    # bays - All bays
    # core
    # detectors - All detectors
    # display - The display
    # network - The network
    # Individual detectors and bays can also be set by including their names.
    bay1: info
# Triggers for actions. Need to have some enabled otherwise nothing ever happens!
triggers:
  # External command handler intended to take direct commands from an external system, ie: Home Assistant.
  # Bay commands require a Bay ID, System Commands don't. See documentation for details.
  # Can only have one of these.
  command:
    type: mqtt_command
    topic: cmd
  # "Sensor" monitors an MQTT topic for a topic changes. Sensors are expected to be a single
  # string, ie: "on"/"off" or "True"/"False"
  garage_door:
    type: mqtt_sensor
    bay: bay1
    to: on
    when_triggered: occupancy
  entry_door:
    type: mqtt_sensor
    bay: bay1
    when_triggered: verify
  # Range based triggering. If movement is detected, take an action. This requires running the range sensor continually.
  range:
    type: range
    enable: true
    detector: range
    when_triggered: occupancy

# Settings for the display. Only one is supported! If you want to build a multi-panel display, treat it as one and do it
# in hardware.
display:
  matrix:
    width: 64  # Columns on the Matrix
    height: 32  # Rows on the Matrix
    gpio_slowdown: 4  # How much to slow down the matrix to prevent flicker.
  strobe_speed: 100 ms
  mqtt_image: True  # Should image updates be sent via MQTT
  mqtt_update_interval: 5 s  # How often should a new image be spent. Keeps from spamming the server.
# Define detectors. These are individual sensing units that then get assigned to a bay later.
detectors:
  range:  # Key here is the Bay ID, which is used elsewhere. IF you see a mention of 'bay_id', this is it.
#    # Range sensors have a type of Range. Obvs.
    type: Range
#    # Name is used for reporting MQTT, as distinct from the key. This will be prepended with the Bay's Name and
#    # appended with "Detector". So "Range" here for "Bay 1" will become "Bay 1 Range Detector"
    name: Range
    sensor:
      type: TFMini
      port: serial0  # System will automatically prefix /dev if not included.
      baud: 115200
      error_margin: "2 cm"  # Amount of distance this sensor can vary and still be counted as 'still'
  front:
    type: Lateral
    name: Front
    sensor:
      type: VL53L1X
      i2c_bus: 1
      i2c_address: 0x33
      enable_board: 0x58
      enable_pin: 3
      distance_mode: medium
      timing: 200ms
  middle:
    type: Lateral
    name: Middle
    sensor:
      type: VL53L1X
      i2c_bus: 1
      i2c_address: 0x32
      enable_board: 0x58
      enable_pin: 2
      distance_mode: medium
      timing: 200ms
  rear:
    type: Lateral
    name: Rear
    sensor:
      type: VL53L1X
      i2c_bus: 1
      i2c_address: 0x31
      enable_board: 0x58
      enable_pin: 1
      distance_mode: medium
      timing: 200ms
bays:
  bay1:
    bay_id: bay1
    name: "Bay 1"
    log_level: debug
    park_time: 120s
    bay_depth: 276in
    longitudinal:
      defaults:
        offset: 42 in
        spread_park: 2 in
        bay_depth: 237 in
      detectors:
        - detector: range
    lateral:
      # Lateral detectors are those that run perpendicular to the path of vehicle's travel.
      defaults:
        offset: 23 in
        spread_ok: 1 in
        spread_warn: 3 in
        side: R
      detectors:
        - detector: front
          intercept: 77.5 in
        - detector: middle
          offset: 22 in
          intercept: 126 in
        - detector: rear
          intercept: 215 in