[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
requires-python = ">=3.13"
name = "Cobrabay"
version = "0.5.0a1"
description = "Cobrabay Parking Guidance System"
authors = [{name="Chris Gill", email="chris@chrisgill.net"}]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Topic :: Home Automation"
]
dependencies = [
    "adafruit-blinka~=9.1.0",
    "adafruit-circuitpython-aw9523~=1.1.16",
    "adafruit-circuitpython-vl53l1x~=1.2.9",
    "gpiozero~=2.0.1",
    # "ha-mqtt-discoverable~=0.23.0",
    #"lgpio~=0.2.2.0",
    "rpi-gpio~=0.7.1",
    "marshmallow~=4.3.0",
    "numpy~=2.5.0",
    "paho-mqtt~=2.1.0",
    "pid~=3.0.4",
    "pillow~=12.3.0",
    "pint~=0.25.2",
    "psutil~=7.2.2",
    "pyserial~=3.5",
    "pyyaml~=6.0.3",
    "rpi-bad-power~=0.1.0",
    "smbus2~=0.6.1",
    # Replace once published
    "rgbmatrix@git+https://github.com/hzeller/rpi-rgb-led-matrix",
    "rgbmultitool@git+https://github.com/chrisgilldc/rgbmultitool",
]

[project.urls]
Homepage = "https://github.com/chrisgilldc/cobrabay"
Issues = "https://github.com/chrisgilldc/cobrabay/issues"

[project.optional-dependencies]
test = [
    "pytest",
    "pint"
]

[project.scripts]
cobrabay = "cobrabay.tools.cli:cbcli"